"""Add extended SoS and use Float

Revision ID: 24b13955be2b
Revises: bc509b74de1b
Create Date: 2016-01-13 23:51:24.460732

"""

# revision identifiers, used by Alembic.
revision = '24b13955be2b'
down_revision = 'bc509b74de1b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('extended_sos', sa.Float(asdecimal=True), nullable=True))
    op.drop_column('result', 'strength_of_schedule')
    op.add_column('result', sa.Column('strength_of_schedule', sa.Float(asdecimal=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'extended_sos')
    op.drop_column('result', 'strength_of_schedule')
    op.add_column('result', sa.Column('strength_of_schedule', sa.Integer(), nullable=True))
    ### end Alembic commands ###
