"""Initial tables

Revision ID: 40b586d66b12
Revises: 
Create Date: 2015-12-29 19:39:09.046694

"""

# revision identifiers, used by Alembic.
revision = '40b586d66b12'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('side',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('side_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['side_id'], ['side.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upload_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['faction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('runner_ident_id', sa.Integer(), nullable=True),
    sa.Column('corp_ident_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['corp_ident_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['runner_ident_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('strength_of_schedule', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('player')
    op.drop_table('identity')
    op.drop_table('tournament')
    op.drop_table('faction')
    op.drop_table('user')
    op.drop_table('side')
    ### end Alembic commands ###
