"""Add cycle and pack codes

Revision ID: 5d6356614f75
Revises: 108eca49452e
Create Date: 2016-01-11 23:24:28.869968

"""

# revision identifiers, used by Alembic.
revision = '5d6356614f75'
down_revision = '108eca49452e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle', sa.Column('code', sa.String(length=16), nullable=False))
    op.add_column('pack', sa.Column('code', sa.String(length=16), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'code')
    op.drop_column('cycle', 'code')
    ### end Alembic commands ###
