"""Add tournament upload Datetime and file information

Revision ID: bc509b74de1b
Revises: f91bacbf0876
Create Date: 2016-01-13 23:30:46.766419

"""

# revision identifiers, used by Alembic.
revision = 'bc509b74de1b'
down_revision = 'f91bacbf0876'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('file_type', sa.Enum('txt', 'json'), nullable=True))
    op.add_column('tournament', sa.Column('filename', sa.String(length=256), nullable=True))
    op.add_column('tournament', sa.Column('uploaded', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament', 'uploaded')
    op.drop_column('tournament', 'filename')
    op.drop_column('tournament', 'file_type')
    ### end Alembic commands ###
