"""Add faction code and identity image_url

Revision ID: df54f2fa989e
Revises: 24b13955be2b
Create Date: 2016-01-16 15:47:27.851495

"""

# revision identifiers, used by Alembic.
revision = 'df54f2fa989e'
down_revision = '24b13955be2b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faction', sa.Column('code', sa.String(length=32), nullable=False))
    op.add_column('identity', sa.Column('image_url', sa.String(length=256), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity', 'image_url')
    op.drop_column('faction', 'code')
    ### end Alembic commands ###
